import Head from "next/head";
import { NFTManager } from "../components/NFTManager";
import ImageNft from "../components/ImageNft";
import { useAccount, useConnect } from "wagmi";
import { NFTDisplay } from "../components/NFTDisplay";
import { MintTextNFT } from "../components/MintTextNFT";
import { TextNFTList } from "../components/TextNFTList";

const Home = () => {
  const { isConnected } = useAccount();

  console.log("接続状態:", isConnected);

  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
      </Head>

      <main>
        <div>
          {isConnected ? (
            <>
              <MintTextNFT />
              <TextNFTList />
            </>
          ) : null}
        </div>
      </main>
    </div>
  );
};

export default Home;
