import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from "next/head";
import { NFTManager } from "../components/nft";
import ImageNft from "../components/ImageNft";
import { useAccount, useConnect } from "wagmi";

const Home = () => {
  const { isConnected } = useAccount();

  console.log("接続状態:", isConnected);

  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <div>
          {isConnected ? (
            <>
              <NFTManager />
              <ImageNft />
            </>
          ) : null}
        </div>
      </main>
    </div>
  );
};

export default Home;
